# Generated by Django 4.1.7 on 2023-03-11 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='upload',
            field=models.FileField(null=True, upload_to=main.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
