# Generated by Django 4.1.7 on 2023-03-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_upload_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='task',
            name='image3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='task',
            name='image4',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='task',
            name='image5',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
