# Generated by Django 4.1.7 on 2023-03-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_task_upload_remove_task_user_task_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='image',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='task',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='task',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='task',
            name='image5',
        ),
    ]
