# Generated by Django 4.1.7 on 2023-03-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_image_task_images_remove_task_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='images',
            new_name='image',
        ),
    ]
