# Generated by Django 4.1.7 on 2023-03-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_images_remove_task_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
