# Generated by Django 4.1.7 on 2023-03-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image_preview',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
