# Generated by Django 4.1.7 on 2023-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_multipleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.AlterField(
            model_name='multipleimage',
            name='images',
            field=models.FileField(upload_to='images/'),
        ),
    ]
