# Generated by Django 4.1.7 on 2023-03-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_multipleimage_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImage',
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default=2, null='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
