# Generated by Django 4.1.7 on 2023-03-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_task_image2_task_image3_task_image4_task_image5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='media\\base\\PL.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image2',
            field=models.ImageField(default='media\\base\\PL.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image3',
            field=models.ImageField(default='media\\base\\PL.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image4',
            field=models.ImageField(default='media\\base\\PL.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image5',
            field=models.ImageField(default='media\\base\\PL.png', upload_to='images/'),
        ),
    ]
